[project]
name = "${app_name}"
version = "${version}"
description = "Your app description here."
authors = [
    {name = "${author}", email = "your.email@example.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "${python_version}"
keywords = []
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
${addon_dependencies}
]


[project.urls]
Homepage = "https://github.com/neuri-ai/qyro"
Repository = "https://github.com/neuri-ai/qyro"
Documentation = "https://qyro.neuri.ai"
"Bug Tracker" = "https://github.com/neuri-ai/qyro/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

include = [
]

exclude = ["tests", "tests.*"]
